### PR TITLE
GitHub project template

### LINKED ISSUE #36: Github: tempalte for python projects
### What is the expected behavior?
Create Github template for python projects.

### PR DESCRIPTION
**Pull request by mickahell**
### Summary
Create a template for project to be ready for the __Qiskit Ecosystem__

### Details and comments
- [x] config file
- [x] tox
- [x] ecosystem.json
- [x] tests actions
- [x] qiskit version check actions
- [x] readme.md
- [x] src
- [x] tests
- [x] in external project 

Closes #36 
Epic #9

### CODE REVIEW

**Comment by mickahell** [comment]
@IceKhan13 what do you thing of that for project template ? :) maybe you have other idea of file to include

**Comment by IceKhan13** [comment]
Looks great!

Let's move it to separate repository. You can create your own for now and later on we either add it in ecosystem as one 
of the community project or move it to `qiskit-community` github org.

Reason I want to move it as separate repository, so we can use `template` functionality of GitHub https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository

**Comment by mickahell** [comment]
> Looks great!
> 
> Let's move it to separate repository. You can create your own for now and later on we either add it in ecosystem as one of the community project or move it to `qiskit-community` github org.
> 
> Reason I want to move it as separate repository, so we can use `template` functionality of GitHub https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository

Oh yeah good thinking :D so, I'm moving it to a local repo on my github account ? Or do you create me directly a repo on the qiskit-community ?

**Comment by mickahell** [comment]
@IceKhan13 the local project : https://github.com/mickahell/qiskit-ecosystem_template
so we can close this PR ?

**Comment by IceKhan13** [comment]
@mickahell I saw your submission! looks good, so we can close this PR 👍 

Submission with project template is in https://github.com/qiskit-community/ecosystem/issues/76

**Pull request closed without merging**
