### PR TITLE
Added passenv to tox.ini

### PR DESCRIPTION
**Pull request by bopardikarsoham**
I have added `passenv = *` in the `[test-env]` section of the tox file as per Issue #161

### CODE REVIEW

**Comment by mickahell** [comment]
Hi :) Nice now we needed to find a way to get the secret var from external repo else, it's a no need for this parameter

**Comment by bopardikarsoham** [comment]
Oh ok so what are the next steps for this PR?

**Comment by bopardikarsoham** [comment]
Um is it something related to kubernetes? @IceKhan13.

**Comment by mickahell** [comment]
Nop, the secrets are related to GitHub for running the CI/CD.

Here, we are not related to where the project are running.

**Comment by IceKhan13** [comment]
Thanks for contribution @bopardikarsoham

**Pull request merged**
