### PR TITLE
Issue 160 | Adaptive lint

### LINKED ISSUE #160: Lint adaptive
### What is the expected enhancement?
Do not use our linter each time.
If `.pylintrc` exist in the external project, use him to run lint test.

### PR DESCRIPTION
**Pull request by mickahell**
### Summary
When adding a repo, if exists, do not erase the existing .pylintrc by the default one.

### Details and comments
- [x] Update the `python_styles_runner.py` `configure_repo()` call

---
Closes #160

### CODE REVIEW

**Comment by mickahell** [comment]
@IceKhan13 Should do the job :)

**Review by IceKhan13 — COMMENTED** [review]
@mickahell will this break if repo has no `.pylintrc` file?

**Comment by mickahell** [comment]
> @mickahell will this break if repo has no `.pylintrc` file?

Nop, it gonna have the same behaviour as the `.coveragerc`, so using the one by default as in the [simple_python_repository](https://github.com/qiskit-community/ecosystem/tree/main/tests/resources/simple_python_repository)

**Review by IceKhan13 — APPROVED** [review]
Sweet!

**Comment by mickahell** [comment]
> Sweet!

Can you merge it for me :) ? I don’t have the right to do it

**Pull request merged**
