### PR TITLE
CI: Json lint

### LINKED ISSUE #120: CI: json lint
### What is the expected enhancement?
Add a json lint in the CI, to check the good syntax of members.json

### PR DESCRIPTION
**Pull request by mickahell**
### Summary
Add a CI check for syntax of any ecosystem/resources/*.json

### Details and comments
- [x] Add tox job
- [x] Add job in tests.yml

Closes #120

### CODE REVIEW

**Comment by mickahell** [comment]
@IceKhan13 can you review it :) thanks

**Review by IceKhan13 — CHANGES_REQUESTED** [review]
maybe it's better to have a test which tests resources file? in that case we will not need any more workflows because we already have workflow for tests

something like
```python
class TestResources(TestCase):
    def test_membership(self):
        with open(self.path_to_members, "r") as members_json_file:
             members_data = json.load(members_json_file)
        self.assertTrue(members_data)
```

so, test would be just testing that json loads working and not throwing `ValueError`

**Comment by mickahell** [comment]
@IceKhan13 

I was more seeing it as lint check and I see unit test as application tests.
Also, I'm checking every json file it has in the resources folder and not only members.json

Else I can put the script in the tox file and have a tox command.


What do you thing ?

**Comment by IceKhan13** [comment]
oh, that is a great idea to put it in tox and run json lint there. But overall main things we need to worry about is members.json. 

BTW, we do not have tests for production `ecosystem/resources/members.json`. In TestsDao we create and use fake `tests/resources/members.json` not to break main one.

**Comment by mickahell** [comment]
done, had it to tox. 

Oh yes, I remembered

> oh, that is a great idea to put it in tox and run json lint there. But overall main things we need to worry about is members.json.
> 
> BTW, we do not have tests for production `ecosystem/resources/members.json`. In TestsDao we create and use fake `tests/resources/members.json` not to break main one.

**Comment by mickahell** [comment]
@IceKhan13 ?

**Comment by mickahell** [comment]
> oh, that is a great idea to put it in tox and run json lint there. But overall main things we need to worry about is members.json.
> 
> BTW, we do not have tests for production `ecosystem/resources/members.json`. In TestsDao we create and use fake `tests/resources/members.json` not to break main one.

and that : https://github.com/qiskit-community/ecosystem/blob/main/tests/test_members_file.py ?

**Review by IceKhan13 — APPROVED** [review]

**Pull request merged**
