### PR TITLE
Avoid annotations errors

### LINKED ISSUE #538: Avoid error annotation on label deletion
### What is the expected enhancement?

Avoid to have those error annotation on label deletion :
Capture d’écran 2023-09-18 à 18 53 05

### PR DESCRIPTION
**Pull request by mickahell**
### Summary

Add condition to avoid annotations error.

### Details and comments

- [x] Add condition on labels removing
- [x] Test [dryrun](https://github.com/mickahell/ecosystem/actions/runs/6289978143)

---
Closes #538

### CODE REVIEW

**Comment by mickahell** [comment]
@frankharkins ready for your review :)

**Review by frankharkins — COMMENTED** [review]
Nice, thanks! Can we remove the `continue-on-error: true`? Or is that still needed?

**Comment by mickahell** [comment]
> Nice, thanks! Can we remove the `continue-on-error: true`? Or is that still needed?

Normally we don't need them anymore, I just keep them to avoid disturbance if we have a misrun function ^^ but we can delete them.

**Review by frankharkins — APPROVED** [review]
Thank you!

**Pull request merged**
