### PR TITLE
Add member before doing tests

### PR DESCRIPTION
**Pull request by frankharkins**
### Summary

The submission workflow is failing as there is no member in the database when updating the test results (see https://github.com/qiskit-community/ecosystem/actions/runs/6017322417/job/16323220183#step:6:82). I believe we can fix this by adding the member before doing the tests.

### CODE REVIEW

**Comment by frankharkins** [comment]
Seems to work (at least doesn't break in same place): https://github.com/frankharkins/ecosystem/actions/runs/6024877417/job/16344457666

**Comment by frankharkins** [comment]
Actually, I don't think this works; the tests are incorrectly being reported as failing

**Comment by frankharkins** [comment]
Actually, this _does_ seem to fix it, it's just the project I chose to test on is reported as failing (this is a bug, but unrelated to #518).

**Comment by mickahell** [comment]
@frankharkins As https://github.com/qiskit-community/ecosystem/pull/519 fix it, do you still want to add the member before running the checks ?

**Review by mickahell — APPROVED** [review]
Good for me. Just I don't really see why you want to add the member before running the test ^^'

**Comment by frankharkins** [comment]
I thought this would add test results to the submission PR, but it doesn't seem to do that either 😅 

I'll close it again as it seems like an inconsequential change

**Pull request closed without merging**
