### PR TITLE
[BUG] Unable to output

### LINKED ISSUE #458: [BUG] Unable to process Output
### Steps to reproduce the problem
The output evolution seems to have import a new bug when an error occur during check: 
see : https://stackoverflow.com/questions/74137120/how-to-fix-or-avoid-error-unable-to-process-file-command-output-successfully

This problem only occur with project who has an error during their check and so in anycase need to adapt for passing our check. The problem does not occur with passing project.

### PR DESCRIPTION
**Pull request by mickahell**
### Summary
Do not join logs by `"\n"` but instead used `" "` to keep them single line friendly with new `GITHUB_OUTPUT` variables.

### Details and comments
- [x] Update join in return logs
- [x] Fixed 2 depreciations I didn't saw last time
- [x] Update unit tests
- [x] Tests run --> https://github.com/mickahell/ecosystem/actions/runs/5683507039/job/15404220026 

---
Closes #458

### CODE REVIEW

**Comment by mickahell** [comment]
@frankharkins I found why and fix it :) ready for your review

**Review by frankharkins — COMMENTED** [review]
Thanks! What do you think about adding a guard to `set_actions_output` to assert there's no newline characters? Might make it easier to debug in the future.

**Comment by mickahell** [comment]
> Thanks! What do you think about adding a guard to `set_actions_output` to assert there's no newline characters? Might make it easier to debug in the future.

Do you mean an if check ?

**Comment by mickahell** [comment]
@frankharkins do you mean something like :
```python
if "\n" in my_string:
   single_ value = " ".join(line.strip() for line in my_string.splitlines())
```
?

**Comment by frankharkins** [comment]
I was thinking more

```python
assert "\n" not in my_string, f"Error: Newlines in github output ({my_string})"

**Comment by mickahell** [comment]
Oh yeah a test case, well see :) 
I'll try that

**Comment by mickahell** [comment]
@frankharkins I applied your suggestion :)
and I did some tests as well : actions [5699620350](https://github.com/mickahell/ecosystem/actions/runs/5699620350) and [5699614358](https://github.com/mickahell/ecosystem/actions/runs/5699614358) everything is working as expected

**Review by frankharkins — APPROVED** [review]
Awesome! Thank you :)

**Pull request merged**
